name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read        # to checkout code
  pages: write          # to deploy
  id-token: write       # to authenticate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm + deps
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build the static site
      - name: Build SvelteKit
        run: pnpm run build

      # Upload the output (default `build/`) as a Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  # Deploy after artifact upload succeeds
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4